BROWSER_PATH = "<BROWSER PATH HERE> %s"
programs = {
    '<PROGRAM NAME HERE>' : '<PROGRAM PATH HERE>',
    'example2' : 'D:\\example1.exe'
}

# WINDOWS ONLY
# Contains all settings, shutdown actions, file explorer
extras = ['explorer','shutdown','restart','logoff','lock','exit']
settings = [
    'about settings',
    'activation settings',
    'appsfeatures settings',
    'appsforwebsites settings',
    'apps-volume settings',
    'autoplay settings',
    'backup settings',
    'recovery settings',
    'batterysaver settings',
    'batterysaver-settings settings',
    'batterysaver-usagedetails settings',
    'bluetooth settings',
    'crossdevice settings',
    'defaultapps settings',
    'developers settings',
    'display settings',
    'screenrotation settings',
    'storagesense settings',
    'maps settings',
    'connecteddevices settings',
    'devices-touchpad settings',
    'mousetouchpad settings',
    'typing settings',
    'findmydevice settings',
    'usb settings',
    'network-airplanemode settings',
    'network-cellular settings',
    'network-directaccess settings',
    'network-dialup settings',
    'network-ethernet settings',
    'network-proxy settings',
    'network-status settings',
    'network-vpn settings',
    'network-wifi settings',
    'network-wifisettings settings',
    'sync settings',
    'datausage settings',
    'network-mobilehotspot settings',
    'lockscreen settings',
    'powersleep settings',
    'multitasking settings',
    'optionalfeatures settings',
    'personalization settings',
    'personalization-background settings',
    'personalization-colors settings',
    'colors settings',
    'personalization-start settings',
    'taskbar settings',
    'themes settings',
    'printers settings',
    'proximity settings',
    'emailandaccounts settings',
    'otherusers settings',
    'workplace settings',
    'dateandtime settings',
    'regionlanguage settings',
    'signinoptions settings',
    'speech settings',
    'privacy settings',
    'privacy-accountinfo settings',
    'privacy-backgroundapps settings',
    'privacy-appdiagnostics settings',
    'privacy-callhistory settings',
    'privacy-calendar settings',
    'privacy-contacts settings',
    'privacy-email settings',
    'privacy-feedback settings',
    'privacy-location settings',
    'privacy-messaging settings',
    'privacy-microphone settings',
    'privacy-motion settings',
    'notifications settings',
    'privacy-notifications settings',
    'privacy-customdevices settings',
    'privacy-radios settings',
    'privacy-speechtyping settings',
    'privacy-tasks settings',
    'privacy-webcam settings',
    'yourinfo settings',
    'easeofaccess-closedcaptioning settings',
    'easeofaccess-highcontrast settings',
    'easeofaccess-keyboard settings',
    'easeofaccess-magnifier settings',
    'easeofaccess-mouse settings',
    'easeofaccess-narrator settings',
    'easeofaccess-otheroptions settings',
    'project settings',
    'tabletmode settings',
    'windowsdefender settings',
    'windowsinsider settings',
    'troubleshoot settings',
    'windowsupdate settings',
    'windowsupdate-action settings',
    'windowsupdate-history settings',
    'windowsupdate-options settings',
    'windowsupdate-restartoptions settings'
]
for i in range(len(settings)):
    extras.append(settings[i])